import { FC } from 'react';
import Head from 'next/head';
import { GetStaticProps } from 'next';
import { Inter } from 'next/font/google';
import axios from 'axios';
import styles from '@/styles/Home.module.css';
import ProjectList from '@/components/ProjectList/ProjectList';
import type { ProjectListProps } from '@/types/project';

const inter = Inter({ subsets: ['latin'] });

export const getStaticProps: GetStaticProps = async () => {
  const { data } = await axios.get(
    `${process.env.NEXT_PUBLIC_API_BASE_URL}/api/projects`
  );
  const projects = data.projects;

  return {
    props: {
      projects,
    },
  };
};

const HomePage: FC<ProjectListProps> = ({ projects }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>Frontend Mentor Projects</h1>
        <ProjectList projects={projects} />
      </main>
    </>
  );
};

export default HomePage;
