import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import ProjectList from '@/components/ProjectList/ProjectList';
import type { Project } from '@/types/project';

const inter = Inter({ subsets: ['latin'] });

const projects: Project[] = [
  {
    id: '1',
    name: 'test',
    description: 'test2',
    technologies: [],
  },
];

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>Frontend Mentor Projects</h1>
        <ProjectList projects={projects} />
      </main>
    </>
  );
};

export default HomePage;
